### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by ww9980** [mivade/IonMD#13]
Hi,

I'm trying to run IonMD however, I was unable to get pass. I'm on `Python2.7.6+GCC4.8.2+Ubuntu` and installed packages required. I'm now facing 2 questions

1. By running `make`, it says `h2xml: Command not found`

2. By running `python runsim.py`, I got `ImportError: cannot import name Params` on line33.

`params` has been installed and updated to the latest version via `pip`, I'm not sure what the problem was. Could you please help me with this?

Thanks.
Fan

**Comment by mivade** [comment]
`h2xml` can be found in the `python-ctypeslib` [package](http://manpages.ubuntu.com/manpages/xenial/en/man1/ctypeslib.1.html).

The `Params` object is a C struct, so if the `.so` is not compiled, it would result in an error.

**Comment by ww9980** [comment]
Thanks Mivade! I've only installed `ctypeslib` instead of `python-ctypeslib`. Now it works. Thanks.
